# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#########################################################
## This file is auto-generated by mkinit. Do not edit. ##
#########################################################
# mkinit flags
__ignore__ = ["logger"]
#########################################################


from aiperf.ui.dashboard.aiperf_dashboard_ui import (
    AIPerfDashboardUI,
)
from aiperf.ui.dashboard.aiperf_textual_app import (
    AIPerfTextualApp,
)
from aiperf.ui.dashboard.aiperf_theme import (
    AIPERF_THEME,
)
from aiperf.ui.dashboard.custom_widgets import (
    MaximizableWidget,
    NonFocusableDataTable,
)
from aiperf.ui.dashboard.progress_dashboard import (
    ProgressDashboard,
)
from aiperf.ui.dashboard.progress_header import (
    ProgressHeader,
)
from aiperf.ui.dashboard.realtime_metrics_dashboard import (
    RealtimeMetricsDashboard,
    RealtimeMetricsTable,
)
from aiperf.ui.dashboard.rich_log_viewer import (
    LogConsumer,
    RichLogViewer,
)
from aiperf.ui.dashboard.worker_dashboard import (
    WorkerDashboard,
)
from aiperf.ui.dashboard.worker_status_table import (
    WORKER_STATUS_STYLES,
    WorkerStatusTable,
)

__all__ = [
    "AIPERF_THEME",
    "AIPerfDashboardUI",
    "AIPerfTextualApp",
    "LogConsumer",
    "MaximizableWidget",
    "NonFocusableDataTable",
    "ProgressDashboard",
    "ProgressHeader",
    "RealtimeMetricsDashboard",
    "RealtimeMetricsTable",
    "RichLogViewer",
    "WORKER_STATUS_STYLES",
    "WorkerDashboard",
    "WorkerStatusTable",
]
