#  SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#  SPDX-License-Identifier: Apache-2.0

from pathlib import Path
from typing import Annotated

from pydantic import Field

from aiperf.common.config.base_config import BaseConfig
from aiperf.common.config.config_defaults import OutputDefaults


class OutputConfig(BaseConfig):
    """
    A configuration class for defining output related settings.
    """

    artifact_directory: Annotated[
        Path,
        Field(
            description="The directory to store all the (output) artifacts generated by\nAI-Perf.",
        ),
    ] = OutputDefaults.ARTIFACT_DIRECTORY
