# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from pathlib import Path
from typing import Annotated

import cyclopts
from pydantic import Field

from aiperf.common.config.base_config import BaseConfig
from aiperf.common.config.config_defaults import OutputDefaults


class OutputConfig(BaseConfig):
    """
    A configuration class for defining output related settings.
    """

    _GROUP_NAME = "Output"

    artifact_directory: Annotated[
        Path,
        Field(
            description="The directory to store all the (output) artifacts generated by AIPerf.",
        ),
        cyclopts.Parameter(
            name=(
                "--output-artifact-dir",
                "--artifact-dir",  # GenAI-Perf
            ),
            group=_GROUP_NAME,
        ),
    ] = OutputDefaults.ARTIFACT_DIRECTORY

    # profile_export_file: Annotated[
    #     Path,
    #     Field(
    #         # TODO: Description is not correct
    #         description="The path where the AIPerf profile export will be generated. \n"
    #         "By default, the profile export will be to profile_export.json. The AIPerf files \n"
    #         "will be exported to <profile_export_file>_aiperf.json and <profile_export_file>_aiperf.csv. \n"
    #         "For example, if the profile export file is profile_export.json, the AIPerf file will\n"
    #         "be exported to profile_export_aiperf.csv. (default: profile_export.json)",
    #     ),
    #     cyclopts.Parameter(
    #         name=(
    #             "--output-profile-export-file",
    #             "--profile-export-file",  # GenAI-Perf
    #         ),
    #         group=_GROUP_NAME,
    #     ),
    # ] = OutputDefaults.PROFILE_EXPORT_FILE
