# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
########################################################################
## 🚩                     mkinit flags                             🚩 ##
########################################################################
__ignore__ = []
########################################################################
## ⚠️        This file is auto-generated by mkinit                 ⚠️ ##
## ⚠️             Do not edit below this line                      ⚠️ ##
########################################################################
from aiperf.common.enums.base_enums import (
    BasePydanticBackedStrEnum,
    BasePydanticEnumInfo,
    CaseInsensitiveStrEnum,
)
from aiperf.common.enums.command_enums import (
    CommandResponseStatus,
    CommandType,
)
from aiperf.common.enums.communication_enums import (
    CommAddress,
    CommClientType,
    CommunicationBackend,
    ZMQProxyType,
)
from aiperf.common.enums.data_exporter_enums import (
    ConsoleExporterType,
    DataExporterType,
    ExportLevel,
)
from aiperf.common.enums.dataset_enums import (
    AudioFormat,
    ComposerType,
    CustomDatasetType,
    DatasetSamplingStrategy,
    ImageFormat,
    PromptSource,
    PublicDatasetType,
    VideoFormat,
    VideoSynthType,
)
from aiperf.common.enums.logging_enums import (
    AIPerfLogLevel,
)
from aiperf.common.enums.media_enums import (
    MediaType,
)
from aiperf.common.enums.message_enums import (
    MessageType,
)
from aiperf.common.enums.metric_enums import (
    BaseMetricUnit,
    BaseMetricUnitInfo,
    EnergyMetricUnit,
    EnergyMetricUnitInfo,
    FrequencyMetricUnit,
    FrequencyMetricUnitInfo,
    GenericMetricUnit,
    MetricFlags,
    MetricOverTimeUnit,
    MetricOverTimeUnitInfo,
    MetricSizeUnit,
    MetricSizeUnitInfo,
    MetricTimeUnit,
    MetricTimeUnitInfo,
    MetricType,
    MetricValueType,
    MetricValueTypeInfo,
    MetricValueTypeVarT,
    PowerMetricUnit,
    PowerMetricUnitInfo,
    TemperatureMetricUnit,
    TemperatureMetricUnitInfo,
)
from aiperf.common.enums.model_enums import (
    ModelSelectionStrategy,
)
from aiperf.common.enums.plugin_enums import (
    AIPerfUIType,
    EndpointType,
    TransportType,
)
from aiperf.common.enums.post_processor_enums import (
    RecordProcessorType,
    ResultsProcessorType,
)
from aiperf.common.enums.service_enums import (
    LifecycleState,
    ServiceRegistrationStatus,
    ServiceRunType,
    ServiceType,
)
from aiperf.common.enums.sse_enums import (
    SSEEventType,
    SSEFieldType,
)
from aiperf.common.enums.system_enums import (
    SystemState,
)
from aiperf.common.enums.telemetry_enums import (
    GPUTelemetryMode,
)
from aiperf.common.enums.timing_enums import (
    CreditPhase,
    RequestRateMode,
    TimingMode,
)
from aiperf.common.enums.worker_enums import (
    WorkerStatus,
)

__all__ = [
    "AIPerfLogLevel",
    "AIPerfUIType",
    "AudioFormat",
    "BaseMetricUnit",
    "BaseMetricUnitInfo",
    "BasePydanticBackedStrEnum",
    "BasePydanticEnumInfo",
    "CaseInsensitiveStrEnum",
    "CommAddress",
    "CommClientType",
    "CommandResponseStatus",
    "CommandType",
    "CommunicationBackend",
    "ComposerType",
    "ConsoleExporterType",
    "CreditPhase",
    "CustomDatasetType",
    "DataExporterType",
    "DatasetSamplingStrategy",
    "EndpointType",
    "EnergyMetricUnit",
    "EnergyMetricUnitInfo",
    "ExportLevel",
    "FrequencyMetricUnit",
    "FrequencyMetricUnitInfo",
    "GPUTelemetryMode",
    "GenericMetricUnit",
    "ImageFormat",
    "LifecycleState",
    "MediaType",
    "MessageType",
    "MetricFlags",
    "MetricOverTimeUnit",
    "MetricOverTimeUnitInfo",
    "MetricSizeUnit",
    "MetricSizeUnitInfo",
    "MetricTimeUnit",
    "MetricTimeUnitInfo",
    "MetricType",
    "MetricValueType",
    "MetricValueTypeInfo",
    "MetricValueTypeVarT",
    "ModelSelectionStrategy",
    "PowerMetricUnit",
    "PowerMetricUnitInfo",
    "PromptSource",
    "PublicDatasetType",
    "RecordProcessorType",
    "RequestRateMode",
    "ResultsProcessorType",
    "SSEEventType",
    "SSEFieldType",
    "ServiceRegistrationStatus",
    "ServiceRunType",
    "ServiceType",
    "SystemState",
    "TemperatureMetricUnit",
    "TemperatureMetricUnitInfo",
    "TimingMode",
    "TransportType",
    "VideoFormat",
    "VideoSynthType",
    "WorkerStatus",
    "ZMQProxyType",
]
