# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
########################################################################
## 🚩                     mkinit flags                             🚩 ##
########################################################################
# Disable mkinit for this module, as MetricRegistry is going to discover
# the metrics.
__submodules__ = []
########################################################################
## ⚠️       This file is auto-generated by `make init-files`       ⚠️ ##
## ⚠️                Do not edit below this line                   ⚠️ ##
########################################################################
__all__ = []
