# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from aiperf.common.enums import GenericMetricUnit, MetricFlags
from aiperf.common.exceptions import NoMetricValue
from aiperf.common.models import ParsedResponseRecord
from aiperf.metrics import BaseRecordMetric
from aiperf.metrics.derived_sum_metric import DerivedSumMetric
from aiperf.metrics.metric_dicts import MetricRecordDict


class OutputTokenCountMetric(BaseRecordMetric[int]):
    """
    Post-processor for calculating Output Token Count metrics from records.

    This is the total number of output tokens generated by the model for one
    individual record.

    Formula:
        Output Token Count = Sum(Output Token Counts)
    """

    tag = "output_token_count"
    header = "Output Token Count"
    short_header = "Output Tokens"
    short_header_hide_unit = True
    unit = GenericMetricUnit.TOKENS
    flags = (
        MetricFlags.PRODUCES_TOKENS_ONLY
        | MetricFlags.LARGER_IS_BETTER
        | MetricFlags.NO_CONSOLE
    )
    required_metrics = None

    def _parse_record(
        self,
        record: ParsedResponseRecord,
        record_metrics: MetricRecordDict,
    ) -> int:
        """
        This method extracts the output token count from the record and returns it.

        Raises:
            NoMetricValue: If the record does not have an output token count.
        """
        if not record.output_token_count:
            raise NoMetricValue("Output token count is missing in the record.")

        return record.output_token_count


class TotalOutputTokensMetric(DerivedSumMetric[int, OutputTokenCountMetric]):
    """
    This is the total number of output tokens generated by the model for
    all records.

    Formula:
        ```
        Total Output Tokens = Sum(Output Token Counts)
        ```
    """

    tag = "total_output_tokens"
    header = "Total Output Tokens"
    short_header = "Total Output"
    short_header_hide_unit = True
    flags = (
        MetricFlags.PRODUCES_TOKENS_ONLY
        | MetricFlags.LARGER_IS_BETTER
        | MetricFlags.NO_CONSOLE
    )
