# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
site_name: AIPerf Documentation
site_description: Documentation for the AIPerf project
site_author: NVIDIA CORPORATION & AFFILIATES

nav:
  - Home: index.md
  - Getting Started:
    - Basic Tutorial: tutorial.md
    - CLI Options: cli_options.md
    - Migrating from GenAI-Perf: migrating.md
  - Advanced Features:
    - Request Cancellation: tutorials/request-cancellation.md
    - Trace Benchmarking: tutorials/trace-benchmarking.md
    - Fixed Schedule: tutorials/fixed-schedule.md
    - Time-based Benchmarking: tutorials/time-based-benchmarking.md
    - Sequence Distributions: tutorials/sequence-distributions.md
    - Goodput: tutorials/goodput.md
  - Reference:
    - Architecture: architecture.md
    - Benchmark Datasets: benchmark_datasets.md
    - Feature Comparison: genai-perf-feature-comparison.md
    - Development: Development.md
  - API Reference: api.md # Generated by tools/generate_api_md.py with GitHub Actions

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
