# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

################################################################################
# This file is auto-generated by mkinit. Do not edit manually.
################################################################################

from aiperf.common.enums.base import (
    CaseInsensitiveStrEnum,
)
from aiperf.common.enums.benchmark_suite import (
    BenchmarkSuiteCompletionTrigger,
    BenchmarkSuiteType,
)
from aiperf.common.enums.command import (
    CommandResponseStatus,
    CommandType,
)
from aiperf.common.enums.communication import (
    CommunicationBackend,
    CommunicationClientAddressType,
    CommunicationClientType,
    ZMQProxyType,
)
from aiperf.common.enums.data_exporter import (
    DataExporterType,
)
from aiperf.common.enums.dataset import (
    AudioFormat,
    ComposerType,
    CustomDatasetType,
    ImageFormat,
    PromptSource,
)
from aiperf.common.enums.endpoints import (
    EndpointType,
    ResponsePayloadType,
)
from aiperf.common.enums.logging import (
    AIPerfLogLevel,
)
from aiperf.common.enums.measurement import (
    MeasurementMode,
)
from aiperf.common.enums.message import (
    MessageType,
    NotificationType,
)
from aiperf.common.enums.metric import (
    MetricTimeType,
    MetricType,
)
from aiperf.common.enums.model import (
    Modality,
    ModelSelectionStrategy,
)
from aiperf.common.enums.post_processor import (
    PostProcessorType,
)
from aiperf.common.enums.service import (
    ServiceRegistrationStatus,
    ServiceRunType,
    ServiceState,
    ServiceType,
)
from aiperf.common.enums.sse import (
    SSEEventType,
    SSEFieldType,
)
from aiperf.common.enums.system import (
    SystemState,
)
from aiperf.common.enums.timing import (
    CreditPhase,
    RequestRateMode,
    TimingMode,
)

__all__ = [
    "AIPerfLogLevel",
    "AudioFormat",
    "BenchmarkSuiteCompletionTrigger",
    "BenchmarkSuiteType",
    "CaseInsensitiveStrEnum",
    "CommandResponseStatus",
    "CommandType",
    "CommunicationBackend",
    "CommunicationClientAddressType",
    "CommunicationClientType",
    "ComposerType",
    "CreditPhase",
    "CustomDatasetType",
    "DataExporterType",
    "EndpointType",
    "ImageFormat",
    "MeasurementMode",
    "MessageType",
    "MetricTimeType",
    "MetricType",
    "Modality",
    "ModelSelectionStrategy",
    "NotificationType",
    "PostProcessorType",
    "PromptSource",
    "RequestRateMode",
    "ResponsePayloadType",
    "SSEEventType",
    "SSEFieldType",
    "ServiceRegistrationStatus",
    "ServiceRunType",
    "ServiceState",
    "ServiceType",
    "SystemState",
    "TimingMode",
    "ZMQProxyType",
]
