# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
########################################################################
## 🚩                     mkinit flags                             🚩 ##
########################################################################
__ignore__ = []
########################################################################
## ⚠️       This file is auto-generated by `make init-files`       ⚠️ ##
## ⚠️                Do not edit below this line                   ⚠️ ##
########################################################################
from aiperf.common.messages.base_messages import (
    ErrorMessage,
    Message,
    RequiresRequestNSMixin,
)
from aiperf.common.messages.command_messages import (
    CommandAcknowledgedResponse,
    CommandErrorResponse,
    CommandMessage,
    CommandResponse,
    CommandSuccessResponse,
    CommandUnhandledResponse,
    ConnectionProbeMessage,
    ProcessRecordsCommand,
    ProcessRecordsResponse,
    ProfileCancelCommand,
    ProfileCompleteCommand,
    ProfileConfigureCommand,
    ProfileStartCommand,
    RealtimeMetricsCommand,
    RegisterServiceCommand,
    ShutdownCommand,
    ShutdownWorkersCommand,
    SpawnWorkersCommand,
    StartRealtimeTelemetryCommand,
    TargetedServiceMessage,
)
from aiperf.common.messages.dataset_messages import (
    ConversationRequestMessage,
    ConversationResponseMessage,
    ConversationTurnRequestMessage,
    ConversationTurnResponseMessage,
    DatasetConfiguredNotification,
)
from aiperf.common.messages.inference_messages import (
    InferenceResultsMessage,
    MetricRecordsData,
    MetricRecordsMessage,
    RealtimeMetricsMessage,
)
from aiperf.common.messages.progress_messages import (
    AllRecordsReceivedMessage,
    ProcessRecordsResultMessage,
    ProfileResultsMessage,
    RecordsProcessingStatsMessage,
)
from aiperf.common.messages.server_metrics_messages import (
    ProcessServerMetricsResultMessage,
    ServerMetricsRecordMessage,
    ServerMetricsStatusMessage,
)
from aiperf.common.messages.service_messages import (
    BaseServiceErrorMessage,
    BaseServiceMessage,
    BaseStatusMessage,
    HeartbeatMessage,
    RegistrationMessage,
    StatusMessage,
)
from aiperf.common.messages.telemetry_messages import (
    ProcessTelemetryResultMessage,
    RealtimeTelemetryMetricsMessage,
    TelemetryRecordsMessage,
    TelemetryStatusMessage,
)
from aiperf.common.messages.worker_messages import (
    WorkerHealthMessage,
    WorkerStatusSummaryMessage,
)

__all__ = [
    "AllRecordsReceivedMessage",
    "BaseServiceErrorMessage",
    "BaseServiceMessage",
    "BaseStatusMessage",
    "CommandAcknowledgedResponse",
    "CommandErrorResponse",
    "CommandMessage",
    "CommandResponse",
    "CommandSuccessResponse",
    "CommandUnhandledResponse",
    "ConnectionProbeMessage",
    "ConversationRequestMessage",
    "ConversationResponseMessage",
    "ConversationTurnRequestMessage",
    "ConversationTurnResponseMessage",
    "DatasetConfiguredNotification",
    "ErrorMessage",
    "HeartbeatMessage",
    "InferenceResultsMessage",
    "Message",
    "MetricRecordsData",
    "MetricRecordsMessage",
    "ProcessRecordsCommand",
    "ProcessRecordsResponse",
    "ProcessRecordsResultMessage",
    "ProcessServerMetricsResultMessage",
    "ProcessTelemetryResultMessage",
    "ProfileCancelCommand",
    "ProfileCompleteCommand",
    "ProfileConfigureCommand",
    "ProfileResultsMessage",
    "ProfileStartCommand",
    "RealtimeMetricsCommand",
    "RealtimeMetricsMessage",
    "RealtimeTelemetryMetricsMessage",
    "RecordsProcessingStatsMessage",
    "RegisterServiceCommand",
    "RegistrationMessage",
    "RequiresRequestNSMixin",
    "ServerMetricsRecordMessage",
    "ServerMetricsStatusMessage",
    "ShutdownCommand",
    "ShutdownWorkersCommand",
    "SpawnWorkersCommand",
    "StartRealtimeTelemetryCommand",
    "StatusMessage",
    "TargetedServiceMessage",
    "TelemetryRecordsMessage",
    "TelemetryStatusMessage",
    "WorkerHealthMessage",
    "WorkerStatusSummaryMessage",
]
