# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
########################################################################
## 🚩                     mkinit flags                             🚩 ##
########################################################################
__ignore__ = []
# Make the list of submodules empty to avoid recursively adding
# everything from those modules into the top-level here.
__submodules__ = []

########################################################################
## 📝        Documentation of all supported mkinit flags           📝 ##
########################################################################
# __submodules__ = []
#   Allow list of submodules to be recursively introspected.
#   By default, this is set to expose everything.
#   An empty list `[]` will cause nothing to be exposed.
#
# __external__ = []
#   Specify external modules to expose the attributes of.
#
# __explicit__ = []
#   Custom explicitly defined names to be added to __all__
#
# __protected__ = []
#   Exposes just the modules, but not their attributes.
#
# __private__ = []
#   Modules that should not be exposed at all.
#
# __ignore__ = []
#   Tells mkinit to ignore particular attributes.
#
########################################################################
## ⚠️       This file is auto-generated by `make init-files`       ⚠️ ##
## ⚠️                Do not edit below this line                   ⚠️ ##
########################################################################
__all__ = []
