# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from typing import Annotated

from pydantic import Field

from aiperf.common.config.base_config import BaseConfig
from aiperf.common.config.cli_parameter import CLIParameter
from aiperf.common.config.config_defaults import ImageDefaults
from aiperf.common.config.groups import Groups
from aiperf.common.enums import ImageFormat


class ImageHeightConfig(BaseConfig):
    """
    A configuration class for defining image height related settings.
    """

    _CLI_GROUP = Groups.IMAGE_INPUT

    mean: Annotated[
        float,
        Field(
            ge=0,
            description="Mean height in pixels for synthetically generated images. Image heights follow a normal distribution "
            "around this mean (±`--image-height-stddev`). Used when `--image-batch-size` > 0 for multimodal vision benchmarking. "
            "Generated images are resized from source images in `assets/source_images` directory.",
        ),
        CLIParameter(
            name=(
                "--image-height-mean",  # GenAI-Perf
            ),
            group=_CLI_GROUP,
        ),
    ] = ImageDefaults.HEIGHT_MEAN

    stddev: Annotated[
        float,
        Field(
            ge=0,
            description="Standard deviation for synthetic image heights in pixels. Creates variability in vertical resolution when > 0, "
            "simulating mixed-resolution image inputs. Heights follow normal distribution. "
            "Set to 0 for uniform image heights.",
        ),
        CLIParameter(
            name=(
                "--image-height-stddev",  # GenAI-Perf
            ),
            group=_CLI_GROUP,
        ),
    ] = ImageDefaults.HEIGHT_STDDEV


class ImageWidthConfig(BaseConfig):
    """
    A configuration class for defining image width related settings.
    """

    _CLI_GROUP = Groups.IMAGE_INPUT

    mean: Annotated[
        float,
        Field(
            ge=0,
            description="Mean width in pixels for synthetically generated images. Image widths follow a normal distribution "
            "around this mean (±`--image-width-stddev`). Combined with `--image-height-mean` to determine image dimensions "
            "and file sizes for multimodal benchmarking.",
        ),
        CLIParameter(
            name=(
                "--image-width-mean",  # GenAI-Perf
            ),
            group=_CLI_GROUP,
        ),
    ] = ImageDefaults.WIDTH_MEAN

    stddev: Annotated[
        float,
        Field(
            ge=0,
            description="Standard deviation for synthetic image widths in pixels. Creates variability in horizontal resolution when > 0, "
            "simulating mixed-resolution image inputs. Widths follow normal distribution. "
            "Set to 0 for uniform image widths.",
        ),
        CLIParameter(
            name=(
                "--image-width-stddev",  # GenAI-Perf
            ),
            group=_CLI_GROUP,
        ),
    ] = ImageDefaults.WIDTH_STDDEV


class ImageConfig(BaseConfig):
    """
    A configuration class for defining image related settings.
    """

    _CLI_GROUP = Groups.IMAGE_INPUT

    width: ImageWidthConfig = ImageWidthConfig()
    height: ImageHeightConfig = ImageHeightConfig()
    batch_size: Annotated[
        int,
        Field(
            ge=0,
            description="Number of images to include in each multimodal request. Supported with `chat` endpoint type for vision-language models. "
            "Each image is generated by randomly sampling and resizing source images from `assets/source_images` directory to specified dimensions. "
            "Set to 0 to disable image inputs. Higher batch sizes test multi-image understanding and increase request payload size.",
        ),
        CLIParameter(
            name=(
                "--image-batch-size",
                "--batch-size-image",  # GenAI-Perf
            ),
            group=_CLI_GROUP,
        ),
    ] = ImageDefaults.BATCH_SIZE

    format: Annotated[
        ImageFormat,
        Field(
            description="Image file format for generated images. Choose `png` for lossless compression (larger files, best quality), "
            "`jpeg` for lossy compression (smaller files, good quality), or `random` to randomly select between PNG and JPEG for each image. "
            "Format affects file size in multimodal requests and encoding overhead.",
        ),
        CLIParameter(
            name=(
                "--image-format",  # GenAI-Perf
            ),
            group=_CLI_GROUP,
        ),
    ] = ImageDefaults.FORMAT
